import { app, BrowserWindow, MenuItemConstructorOptions, Menu } from 'electron';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
  
    },
    
  });
 
  setupMenuHandlingForPlatform(mainWindow, customMenu);
  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
//app.on('ready', createWindow);

  app.whenReady().then(() => {
      createWindow();
  });

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});
// check if app is packaged
app.isPackaged ? console.log("App is packaged") : console.log("App is in development mode");

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

function setupMenuHandlingForPlatform(window: BrowserWindow, updateMenuFunction: (window: BrowserWindow | null) => void): void {
  if (process.platform === 'darwin') {
    window.on('focus', () => {
      updateMenuForPlatform(window, updateMenuFunction);
    })
  }
  updateMenuForPlatform(window, updateMenuFunction);
}



function updateMenuForPlatform(window: BrowserWindow, updateMenuFunction: (window: BrowserWindow | null) => void) {
  updateMenuFunction(process.platform !== 'darwin' ? window : null);
}

function customMenu(window: BrowserWindow | null) {
  const shouldShowDevTools = !app.isPackaged;
  const menuTemplate: MenuItemConstructorOptions[] = [
    ...(process.platform === 'darwin' ? [{ role: 'appMenu' }] : []) as MenuItemConstructorOptions[],
    {
      label: '&File',
      submenu: [
        { type: 'separator' },
        { role: 'close' },
        { type: 'separator' },
        { role: 'quit' }
      ] as MenuItemConstructorOptions[]
    },
    {
      label: '&Edit',
      submenu: [
        { role: 'cut' },
        { role: 'copy' },
        { role: 'paste' },
        { role: 'delete' },
        { type: 'separator'},
        { role: 'selectAll' }
      ] as MenuItemConstructorOptions[]
    },
    {
      label: '&View',
      submenu: [
        ...(
          shouldShowDevTools ? [
            { role: 'reload' },
            { role: 'forceReload' },
            { role: 'toggleDevTools' },
            { type: 'separator' }
          ] : [] as MenuItemConstructorOptions[]),
        { role: 'resetZoom' },
        { role: 'zoomIn' },
        { role: 'zoomOut' }
      ] as MenuItemConstructorOptions[]
    },
    {
      label: '&Window',
      submenu: [
        { role: 'minimize' },
        { role: 'zoom' },
        { role: 'close' }
      ]
    },
    
  ];
  const menu = Menu.buildFromTemplate(menuTemplate);

if (window) {
  window.setMenu(menu);
} else {
  Menu.setApplicationMenu(menu);
}
}
  
/*app.on('ready', () => {
  customMenu();
});
// should not be like this will change later

*/

